    - name: Adding Rudder Repo Key
      apt_key:
        url: "{{ rudder_apt_key }}"
        state: present
      become: true

    - name: Adding Rudder Repo
      apt_repository:
        repo: "{{ rudder_apt_repo }}"
        state: present
      become: true
      register: result
      until: result is successful