    - name: Adding Rudder Repo Key
      rpm_key:
        key: "{{ rudder_rpm_key }}"
        state: present
      become: true

    - name: Adding Rudder Repo
      yum_repository:
        description: "Rudder"
        name: "Rudder"
        baseurl: "{{ rudder_rpm_repo }}"
        gpgcheck: true
        gpgkey: "{{ rudder_rpm_key }}"
        state: present
      become: true
