:doc_dir: normation/rudder/docs

= Rudder Ansible Collection
Julien Briault <julien.briault@rudder.io>

== Synopsis
This Ansible collection allows to manage and interact with one or more Rudder instances.
It was created in order to gather all the necessary tools for a good integration of Ansible with Rudder.

This collection allows you to:

        . Provides a plugin that extracts the inventory from Rudder and transforms it into Ansible format so that it can be retrieved (in CLI, in Ansible Tower/AWX).

        . An armada of roles that allow each to deploy a particular element:
            * _deploy-rudder-agent_ as the name suggests, allows you to deploy and configure a Rudder agent.
            * _deploy-rudder-server_ allows you to deploy, provision and configure the nodes properties of a root server.
            * _deploy-rudder-relay_ allows you to deploy a relay server and configure it.
            * _manage-rudder-repository_ allows the management of private Rudder repos.

For more information on each of these parts, you can follow the user documentation **here**.
