---
rudder_apt_key: "{{ rudder_key_url+'/apt/rudder_apt_key.pub' }}"

rudder_apt_repo: "{{ 'deb https://'+rudder_repo_username+':'+rudder_repo_password+'@'+rudder_repo+'/apt/'+rudder_version|string+'/ '+ansible_distribution_release+' main' }}"

rudder_key_url: "{{ 'https://'+rudder_repo }}"

rudder_rpm_key: "{{ rudder_repo_username+':'+rudder_repo_password+'@'+rudder_key_url+'/rpm/rudder_rpm_key.pub' }}"

rudder_rpm_repo: "{{ 'https://'+rudder_repo_username+':'+rudder_repo_password+'@'+rudder_repo+'/rpm/'+rudder_version|string+'/RHEL_$releasever/' }}"

rudder_zypper_repo: "{{ 'https://'+rudder_repo_username+':'+rudder_repo_password+'@'+rudder_repo+'/rpm/'+rudder_version|string+'/SLES_15/' }}"

rudder_version: 6.2

rudder_repo: download.rudder.io
