---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
    - name: ubuntu2004
      image: geerlingguy/docker-ubuntu2004-ansible:latest
    - name: centos8
      image: geerlingguy/docker-centos8-ansible:latest

provisioner:
  name: ansible

verifier:
  name: ansible
