# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get install -y python sudo bash ca-certificates gpg-agent && apt-get clean; fi
RUN if [ $(command -v zypper) ]; then zypper --non-interactive install dbus-1 systemd-sysvinit python python-xml sudo && zypper --non-interactive clean --all; fi
RUN if [ $(command -v zypper) ]; then cp /usr/lib/systemd/system/dbus.service /etc/systemd/system/; fi
