    - name: Adding Rudder Repo Key
      rpm_key:
        key: "{{ rudder_rpm_key }}"
        state: present
      become: true

    - name: Adding Rudder Repo
      zypper_repository:
        description: "Rudder"
        name: "Rudder"
        repo: "{{ rudder_zypper_repo }}"
        disable_gpg_check: false
        auto_import_keys: yes
        state: present
      become: true

    - name: sles | Installing Rudder Agent
      zypper:
        name: rudder-agent
        state: present
      become: true
      register: result
      until: result is successful
