---
server_version: 8.3
rudder_repository_username: ""
rudder_repository_password: ""
rudder_repository: repository.rudder.io
rudder_repository_url: ""
update_cache: yes
apt_key_url: ""
rpm_key_url: ""
