---
galaxy_info:
  role_name: rudder_agent_linux
  namespace: rudder
  author: Rudder
  description: Ansible role to install Rudder Agent on GNU/Linux
  company: Rudder
  license: GPLv3
  min_ansible_version: 2.9
  galaxy_tags:
  - rudder
  - automation
  - compliance
  - audit

  platforms:
    - name: Ubuntu
      versions:
        - all

    - name: Debian
      versions:
        - all

    - name: SLES
      versions:
         - all

    - name: EL
      versions:
        - all

dependencies:
  - role: rudder_repository
    vars:
      repository: "{{ rudder_repository }}"
      repository_username: "{{ rudder_repository_username }}"
      repository_password: "{{ rudder_repository_password }}"
      update_cache: yes
      rudder_version: "{{ agent_version }}"
