---
rudder_version: 9.0

repository: "repository.rudder.io"
repository_url: ""
repository_username: ""
repository_password: ""
rudder_update_cache: yes

_rudder_modern_debian: >-
  {{
    (ansible_facts['distribution'] == 'Ubuntu' and ansible_facts['distribution_major_version'] | int >= 24)
    or
    (ansible_facts['distribution'] == 'Debian' and ansible_facts['distribution_major_version'] | int >= 13)
  }}

effective_rudder_apt_key_url: >-
  {{ rudder_apt_key_url | default(
    'https://repository.rudder.io/apt/rudder_apt_key.gpg'
    if (
      (ansible_facts['distribution'] == 'Ubuntu' and ansible_facts['distribution_major_version'] | int >= 24)
      or
      (ansible_facts['distribution'] == 'Debian' and ansible_facts['distribution_major_version'] | int >= 13)
    )
    else 'https://repository.rudder.io/apt/rudder_apt_key.pub'
  ) }}

effective_rpm_key_url: >-
  {{ rudder_rpm_key_url | default(
    'https://repository.rudder.io/rudder_release_key.pub' if rudder_version is version_compare('8.3', '>=')
    else 'https://repository.rudder.io/rpm/rudder_rpm_key.pub',
    true
  ) }}
